# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitvelocity < Formula
  desc "GitVelocity CLI — a thin client over the GitVelocity MCP server"
  homepage "https://github.com/headlinevc/gitvelocity-cli"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/headlinevc/gitvelocity-cli/releases/download/v0.1.0/gitvelocity_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "cc7ef07df509d82a5b712106f506503e17c70792ebb57edf483e076a13a537a4"

      define_method(:install) do
        bin.install "gv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/headlinevc/gitvelocity-cli/releases/download/v0.1.0/gitvelocity_0.1.0_Darwin_arm64.tar.gz"
      sha256 "9db096568c3eb327f9886c79c8e5ac83bef5d037eba4e63c4a67dfac5ffc9958"

      define_method(:install) do
        bin.install "gv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/headlinevc/gitvelocity-cli/releases/download/v0.1.0/gitvelocity_0.1.0_Linux_x86_64.tar.gz"
      sha256 "da540b8a9f72776f260a269758dde7c02842d73906dac3c095ae5c357858903d"
      define_method(:install) do
        bin.install "gv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/headlinevc/gitvelocity-cli/releases/download/v0.1.0/gitvelocity_0.1.0_Linux_arm64.tar.gz"
      sha256 "104cfa89343f515d7cf665bf7ebaba674355fe1b9d4f22f753d2c2eba78bd5f5"
      define_method(:install) do
        bin.install "gv"
      end
    end
  end

  test do
    system "#{bin}/gv", "version"
  end
end
