# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitvelocity < Formula
  desc "GitVelocity CLI — a thin client over the GitVelocity MCP server"
  homepage "https://github.com/headlinevc/gitvelocity-cli-dist"
  version "0.1.2"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/headlinevc/gitvelocity-cli-dist/releases/download/v0.1.2/gitvelocity_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "2a42a9e57aa04e72e39fbb8bc7dcab2f805f7e845ddcdc5768b9777f1964546e"

      define_method(:install) do
        bin.install "gv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/headlinevc/gitvelocity-cli-dist/releases/download/v0.1.2/gitvelocity_0.1.2_Darwin_arm64.tar.gz"
      sha256 "e7be4d948fb2119941f8817562a5002b516cceb5e42fd3ed7b88403bbffc1765"

      define_method(:install) do
        bin.install "gv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/headlinevc/gitvelocity-cli-dist/releases/download/v0.1.2/gitvelocity_0.1.2_Linux_x86_64.tar.gz"
      sha256 "92fa51d10edde815b45a6c6ec2a8ce491d38354d250f6d665d240a227efab37a"
      define_method(:install) do
        bin.install "gv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/headlinevc/gitvelocity-cli-dist/releases/download/v0.1.2/gitvelocity_0.1.2_Linux_arm64.tar.gz"
      sha256 "efc7c02923e49a22e25dbfa4f16a9a52a9b43f6cb8e657125b1b725dd1fd7b7e"
      define_method(:install) do
        bin.install "gv"
      end
    end
  end

  test do
    system "#{bin}/gv", "version"
  end
end
