# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Searchlight < Formula
  desc "Searchlight CLI — a thin client over the Searchlight MCP server"
  homepage "https://github.com/headlinevc/searchlight-cli"
  version "0.1.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/headlinevc/searchlight-cli/releases/download/v0.1.0/searchlight_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "a269d2733ce1ef43a885bb19971335b0c77dc1d13dd33e803501bb4ac525f48d"

      define_method(:install) do
        bin.install "searchlight"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/headlinevc/searchlight-cli/releases/download/v0.1.0/searchlight_0.1.0_Darwin_arm64.tar.gz"
      sha256 "d9a599e827af86fb0c2fdd24379f6872a5ba36ae4b74b9a8a33b22d045d9d28c"

      define_method(:install) do
        bin.install "searchlight"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/headlinevc/searchlight-cli/releases/download/v0.1.0/searchlight_0.1.0_Linux_x86_64.tar.gz"
      sha256 "8cba4740e0f07458797cf8a5fa6704b9af9cded3a33c1b463edb7842756224fb"
      define_method(:install) do
        bin.install "searchlight"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/headlinevc/searchlight-cli/releases/download/v0.1.0/searchlight_0.1.0_Linux_arm64.tar.gz"
      sha256 "c5cf70d1e387b704df2f64effd9359a940f83c620540f64e845a1bc550fccc36"
      define_method(:install) do
        bin.install "searchlight"
      end
    end
  end

  test do
    system "#{bin}/searchlight", "version"
  end
end
